name: dojo_warehouse
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dojo_dbt_w12
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wcs2025
      MYSQL_DATABASE: dojo_dbt_w12
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  importer:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/app # <-- Monte le dossier actuel (. = ton dossier projet sur ton PC) dans le dossier /app dans le conteneur.
    command: python connect_mysql.py

  dbt:
    build: .
    container_name: dbt_runner 
    depends_on:
      - mysql
    volumes:
      - .:/app 
    working_dir: /app/dojo_dbt_w12 # toutes les commandes dbt seront exécutées depuis le projet 
    environment:
      DBT_PROFILES_DIR: /app/docker_profiles
    stdin_open: true
    tty: true

volumes:
  mysql_data:
